-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID
, TO_CHAR(START_DATE, 'YYYY-MM-DD') as START_DATE
, TO_CHAR(END_DATE, 'YYYY-MM-DD') as END_DATE
, case when END_DATE - START_DATE + 1 >= 30 then '장기 대여' else '단기 대여' end as RENT_TYPE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09'
order by HISTORY_ID desc;